### ISSUE TITLE
Please delete this repository

### ISSUE THREAD

**Issue by briandfoy** [shlomif/mastering-perl#1]
It's an old version of the book and it was never meant to be available past the period when I was writing it. This is copyrighted material that is not available under any open source license.

**Comment by shlomif** [comment]
Hi @briandfoy ! I nullified/reset the history of the git repository itself without deleting the GitHub record, thus preserving the stars, watches, forks and this issue report. This should be enough to comply with your request. Closing as FIXED.

**Comment by briandfoy** [comment]
please completely delete this repository. I don't want my copyrighted material here at all.

**Comment by shlomif** [comment]
@briandfoy : your copyrighted material is no longer here.

**Comment by shlomif** [comment]
Just to get the record's straight. Here is a proof that this repository no longer hosts your copyrighted material

```
shlomif@telaviv1:~$ git clone git@github.com:shlomif/mastering-perl.git
Cloning into 'mastering-perl'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Receiving objects: 100% (12/12), done.
Resolving deltas: 100% (3/3), done.
Checking connectivity... done.
shlomif@telaviv1:~$ cd mastering-perl/
shlomif@telaviv1:~/mastering-perl$ git log | cat
commit bb9092192e3cb9ca04e3dc9b2af5ec28e260b9fe
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue Mar 29 15:12:03 2016 +0300

    Add more links

commit 4aa7edfec5a610337899e37c6c7b178a134901c6
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue Mar 29 15:01:44 2016 +0300

    add the links for learning perl.

commit 3aa3ae82b0be1565c9f2be6d1952835e005c6817
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue Mar 29 14:55:34 2016 +0300

    add more.

commit bafc11abdfffb8bddb2d734fc2b469dd0039455f
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue Mar 29 14:31:04 2016 +0300

    add the new README for the history reset.
shlomif@telaviv1:~/mastering-perl$ 
```

**Comment by briandfoy** [comment]
You need to change the description of this repo to remove my name.

**Comment by shlomif** [comment]
On Mon, 26 Sep 2016 11:38:46 -0700
brian d foy notifications@github.com wrote:

> You need to change the description of this repo to remove my name.

Done.

## 

---

Shlomi Fish       http://www.shlomifish.org/
First stop for Perl beginners - http://perl-begin.org/

The greatest threat to authors and creative artists is not piracy — it's
obscurity.
    — http://radar.oreilly.com/2006/08/piracy-is-progressive-taxation.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by cl0ne** [comment]
NB: all examples from the book are publicly available [at O'Reilly's GitLab](https://resources.oreilly.com/examples/9780596527242/).
